const fs = require('fs');
const exec = require('child_process');

let version = exec
  .execSync('git describe --tags --abbrev=0')
  .toString()
  .trim();
let revision = exec
  .execSync('git rev-parse --short HEAD')
  .toString()
  .trim();
let branch = exec
  .execSync('git rev-parse --abbrev-ref HEAD')
  .toString()
  .trim();

const content = `// This file is automatically generated by prebuild.js
export const git = {
  version: '${version}',
  revision: '${revision}',
  branch: '${branch}'
};
`;

console.log(content);

fs.writeFileSync('src/environments/git.ts', content, {
  encoding: 'utf8'
});

console.log('src/environments/git.ts written to disk');
